on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  check-dnm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        if: github.event.label.name == 'do not merge' && github.event.action == 'labeled'
        with:
          script: |
            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Do Not Merge",
              head_sha: context.payload.pull_request.head.sha,
              conclusion: "failure"
            })
      - uses: actions/github-script@v7
        if: github.event.label.name == 'do not merge' && github.event.action == 'unlabeled'
        with:
          script: |
            github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: "Do Not Merge",
              head_sha: context.payload.pull_request.head.sha,
              conclusion: "success"
            })
