on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  check-dnm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        if: github.event.label.name == 'do not merge' && github.event.pull_request.action == 'labeled'
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['labeled']
            })
      - uses: actions/github-script@v7
        if: github.event.label.name == 'do not merge' && github.event.pull_request.action == 'unlabeled'
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['unlabeled']
            })
