on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-dnm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        if: github.actor == 'chingor13'
        with:
          script: |
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.event.pull_request.number,
              labels: [
                {name: 'foo'}
              ]
            })
